# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('newsubmit', 'NewSubmit'), ('pass', 'Pass')], default='newsubmit', max_length=10),
        ),
    ]
